# Caracteres unicode
print('Hola\u0020World')
print('Notacion simple:', '\u0041')
print('Notacion extendida:', '\U00000041')
print('Notacion hexadecimal:', '\x41')
print('Corazon:', '\u2665')
print('Cara sonriendo:', '\U0001f600')
print('Serpiente:', '\U0001F40D')
# Caracteres ASCII
caracter = chr(65)
print(f'A mayuscula: {caracter}')
caracter = chr(64)
print(f'Simbolo @: {caracter}')
caracter = chr(97)
print(f'a minuscula: {caracter}')
